# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# make_tile.py
# Created on: 2018-03-22 11:17:07.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
Enhance_MapServer = "GIS Servers\\arcgis on cipgis.canadaeast.cloudapp.azure.com (publisher)\\PythonParty\\Enhance.MapServer"
Output_Map_Service_URL = ""

# Process: Create Map Server Cache
arcpy.CreateMapServerCache_server(Enhance_MapServer, "C:\\arcgisserver\\directories\\arcgiscache", "NEW", "CUSTOM", "9", "96", "256 x 256", "", "-34655800 39310000", "145000000;85000000;50000000;30000000;17500000;10000000;6000000;3500000;2000000", "JPEG", "75", "COMPACT")

