# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# modelBuilder1.py
# Created on: 2018-03-20 15:53:01.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# an output to see how the extra parameters can be used in upload server definition

# Local variables:
SeaIceFraction_2041_20yr_MAM_rcp85_sd = "C:\\Data\\CCCP\\CMIP5_SD_automation_ver_1-0\\SeaIceFraction_2041_20yr_MAM_rcp85.sd"
arcgis_on_cipgis_canadaeast_cloudapp_azure_com__publisher_ = "C:\\Users\\jamesr\\AppData\\Roaming\\Esri\\Desktop10.4\\ArcCatalog\\arcgis on cipgis.canadaeast.cloudapp.azure.com (publisher)"
SOAP_Service_URL = ""
REST_Service_URL = ""
Hosted_Map_Service_Item_ID = ""
Hosted_Feature_Service_Item_ID = ""
Cached_Service = ""

# Process: Upload Service Definition
# params: sd file, connection, overridden service name, cluster (leave alone), specify existing folder, folder name, start service, other defaults
arcpy.UploadServiceDefinition_server(SeaIceFraction_2041_20yr_MAM_rcp85_sd, arcgis_on_cipgis_canadaeast_cloudapp_azure_com__publisher_, "MyServiceName", "", "EXISTING", "CMIP5_SeaIceFraction", "STARTED", "USE_DEFINITION", "NO_SHARE_ONLINE", "PRIVATE", "NO_SHARE_ORGANIZATION", "")

